#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# (c) Copyright 2016 - 2022 Xilinx, Inc. All rights reserved.
export TE_IUT_TA_NAME="IUT"
export TE_IUT_SOC_TA_NAME="SoC"
export TE_TST1_TA_NAME="Peer"
export TE_LOG_LISTENER_TA_NAME="LogListener"

source "${TE_BASE}"/engine/builder/te_ta_ssh_helper

: ${TS_TEST_AGENTS:=TE_IUT TE_IUT_SOC TE_TST1 TE_LOG_LISTENER}

te_ta_list_detect_type_with_signature ${TS_TEST_AGENTS}
